version: "3.7"

services:
  emulator:
    image: ghcr.io/badrap/emulator:v0.8.4
    environment:
      APP_URL: http://app:5000/app
    ports:
      - "4004:4004"

  app:
    build:
      target: base
      context: .
    volumes:
      - .:/home/app/workdir:ro
    environment:
      FLASK_ENV: development
      PYTHONUNBUFFERED: "1"
      API_URL: http://emulator:4004/api
      API_TOKEN: 111111111-2222-3333-44444-555555555555
    ports:
      - "5000:5000"
